(ns clj-hisoutensoku.tables)

(def vk-key-table
 {:lbutton 0x01
  :rbutton 0x02
  :cancel 0x03
  :mbutton 0x04
  :back 0x08
  :tab 0x09
  :clear 0x0c
  :return 0x0d
  :shift 0x10
  :control 0x11
  :menu 0x12
  :pause 0x13
  :capital 0x14
  :escape 0x1b
  :space 0x20
  :prior 0x21
  :next 0x22
  :end 0x23
  :home 0x24
  :left 0x25
  :up 0x26
  :right 0x27
  :down 0x28
  :select 0x29
  :print 0x2a
  :execute 0x2b
  :snapshot 0x2c
  :insert 0x2d
  :delete 0x2e
  :help 0x2f
  :0 0x30
  :1 0x31
  :2 0x32
  :3 0x33
  :4 0x34
  :5 0x35
  :6 0x36
  :7 0x37
  :8 0x38
  :9 0x39
  :a 0x41
  :b 0x42
  :c 0x43
  :d 0x44
  :e 0x45
  :f 0x46
  :g 0x47
  :h 0x48
  :i 0x49
  :j 0x4a
  :k 0x4b
  :l 0x4c
  :m 0x4d
  :n 0x4e
  :o 0x4f
  :p 0x50
  :q 0x51
  :r 0x52
  :s 0x53
  :t 0x54
  :u 0x55
  :v 0x56
  :w 0x57
  :x 0x58
  :y 0x59
  :z 0x5a
  :numpad0 0x60
  :numpad1 0x61
  :numpad2 0x62
  :numpad3 0x63
  :numpad4 0x64
  :numpad5 0x65
  :numpad6 0x66
  :numpad7 0x67
  :numpad8 0x68
  :numpad9 0x69
  :multiply 0x6a
  :* 0x6a
  :+ 0x6b
  :add 0x6b
  :separator 0x6c
  :- 0x6d
  :subtract 0x6d
  :decimal 0x6e
  :divide 0x6f
  :f1 0x70
  :f2 0x71
  :f3 0x72
  :f4 0x73
  :f5 0x74
  :f6 0x75
  :f7 0x76
  :f8 0x77
  :f9 0x78
  :f10 0x79
  :f11 0x7a
  :f12 0x7b
  :f13 0x7c
  :f14 0x7d
  :f15 0x7e
  :f16 0x7f
  :f17 0x80
  :f18 0x81
  :f19 0x82
  :f20 0x83
  :f21 0x84
  :f22 0x85
  :f23 0x86
  :f24 0x87
  :numlock 0x90
  :scroll 0x91
  :lshift 0xa0
  :rshift 0xa1
  :lcontrol 0xa2
  :rcontrol 0xa3
  :lmenu 0xa4
  :rmenu 0xa5
  :play 0xfa
  :zoom 0xfb})

(def robot-key-table
 {:0 java.awt.event.KeyEvent/VK_0
  :1 java.awt.event.KeyEvent/VK_1
  :2 java.awt.event.KeyEvent/VK_2
  :3 java.awt.event.KeyEvent/VK_3
  :4 java.awt.event.KeyEvent/VK_4
  :5 java.awt.event.KeyEvent/VK_5
  :6 java.awt.event.KeyEvent/VK_6
  :7 java.awt.event.KeyEvent/VK_7
  :8 java.awt.event.KeyEvent/VK_8
  :9 java.awt.event.KeyEvent/VK_9
  :a java.awt.event.KeyEvent/VK_A
  :accept java.awt.event.KeyEvent/VK_ACCEPT
  :add java.awt.event.KeyEvent/VK_ADD
  :again java.awt.event.KeyEvent/VK_AGAIN
  :all_candidates java.awt.event.KeyEvent/VK_ALL_CANDIDATES
  :alphanumeric java.awt.event.KeyEvent/VK_ALPHANUMERIC
  :alt java.awt.event.KeyEvent/VK_ALT
  :alt_graph java.awt.event.KeyEvent/VK_ALT_GRAPH
  :ampersand java.awt.event.KeyEvent/VK_AMPERSAND
  :asterisk java.awt.event.KeyEvent/VK_ASTERISK
  :at java.awt.event.KeyEvent/VK_AT
  :b java.awt.event.KeyEvent/VK_B
  :back_quote java.awt.event.KeyEvent/VK_BACK_QUOTE
  :back_slash java.awt.event.KeyEvent/VK_BACK_SLASH
  :back_space java.awt.event.KeyEvent/VK_BACK_SPACE
  :begin java.awt.event.KeyEvent/VK_BEGIN
  :braceleft java.awt.event.KeyEvent/VK_BRACELEFT
  :braceright java.awt.event.KeyEvent/VK_BRACERIGHT
  :c java.awt.event.KeyEvent/VK_C
  :cancel java.awt.event.KeyEvent/VK_CANCEL
  :caps_lock java.awt.event.KeyEvent/VK_CAPS_LOCK
  :circumflex java.awt.event.KeyEvent/VK_CIRCUMFLEX
  :clear java.awt.event.KeyEvent/VK_CLEAR
  :close_bracket java.awt.event.KeyEvent/VK_CLOSE_BRACKET
  :code_input java.awt.event.KeyEvent/VK_CODE_INPUT
  :colon java.awt.event.KeyEvent/VK_COLON
  :comma java.awt.event.KeyEvent/VK_COMMA
  :compose java.awt.event.KeyEvent/VK_COMPOSE
  :context_menu java.awt.event.KeyEvent/VK_CONTEXT_MENU
  :control java.awt.event.KeyEvent/VK_CONTROL
  :convert java.awt.event.KeyEvent/VK_CONVERT
  :copy java.awt.event.KeyEvent/VK_COPY
  :cut java.awt.event.KeyEvent/VK_CUT
  :d java.awt.event.KeyEvent/VK_D
  :dead_abovedot java.awt.event.KeyEvent/VK_DEAD_ABOVEDOT
  :dead_abovering java.awt.event.KeyEvent/VK_DEAD_ABOVERING
  :dead_acute java.awt.event.KeyEvent/VK_DEAD_ACUTE
  :dead_breve java.awt.event.KeyEvent/VK_DEAD_BREVE
  :dead_caron java.awt.event.KeyEvent/VK_DEAD_CARON
  :dead_cedilla java.awt.event.KeyEvent/VK_DEAD_CEDILLA
  :dead_circumflex java.awt.event.KeyEvent/VK_DEAD_CIRCUMFLEX
  :dead_diaeresis java.awt.event.KeyEvent/VK_DEAD_DIAERESIS
  :dead_doubleacute java.awt.event.KeyEvent/VK_DEAD_DOUBLEACUTE
  :dead_grave java.awt.event.KeyEvent/VK_DEAD_GRAVE
  :dead_iota java.awt.event.KeyEvent/VK_DEAD_IOTA
  :dead_macron java.awt.event.KeyEvent/VK_DEAD_MACRON
  :dead_ogonek java.awt.event.KeyEvent/VK_DEAD_OGONEK
  :dead_semivoiced_sound java.awt.event.KeyEvent/VK_DEAD_SEMIVOICED_SOUND
  :dead_tilde java.awt.event.KeyEvent/VK_DEAD_TILDE
  :dead_voiced_sound java.awt.event.KeyEvent/VK_DEAD_VOICED_SOUND
  :decimal java.awt.event.KeyEvent/VK_DECIMAL
  :delete java.awt.event.KeyEvent/VK_DELETE
  :divide java.awt.event.KeyEvent/VK_DIVIDE
  :dollar java.awt.event.KeyEvent/VK_DOLLAR
  :down java.awt.event.KeyEvent/VK_DOWN
  :e java.awt.event.KeyEvent/VK_E
  :end java.awt.event.KeyEvent/VK_END
  :enter java.awt.event.KeyEvent/VK_ENTER
  :equals java.awt.event.KeyEvent/VK_EQUALS
  :escape java.awt.event.KeyEvent/VK_ESCAPE
  :euro_sign java.awt.event.KeyEvent/VK_EURO_SIGN
  :exclamation_mark java.awt.event.KeyEvent/VK_EXCLAMATION_MARK
  :f java.awt.event.KeyEvent/VK_F
  :f1 java.awt.event.KeyEvent/VK_F1
  :f10 java.awt.event.KeyEvent/VK_F10
  :f11 java.awt.event.KeyEvent/VK_F11
  :f12 java.awt.event.KeyEvent/VK_F12
  :f13 java.awt.event.KeyEvent/VK_F13
  :f14 java.awt.event.KeyEvent/VK_F14
  :f15 java.awt.event.KeyEvent/VK_F15
  :f16 java.awt.event.KeyEvent/VK_F16
  :f17 java.awt.event.KeyEvent/VK_F17
  :f18 java.awt.event.KeyEvent/VK_F18
  :f19 java.awt.event.KeyEvent/VK_F19
  :f2 java.awt.event.KeyEvent/VK_F2
  :f20 java.awt.event.KeyEvent/VK_F20
  :f21 java.awt.event.KeyEvent/VK_F21
  :f22 java.awt.event.KeyEvent/VK_F22
  :f23 java.awt.event.KeyEvent/VK_F23
  :f24 java.awt.event.KeyEvent/VK_F24
  :f3 java.awt.event.KeyEvent/VK_F3
  :f4 java.awt.event.KeyEvent/VK_F4
  :f5 java.awt.event.KeyEvent/VK_F5
  :f6 java.awt.event.KeyEvent/VK_F6
  :f7 java.awt.event.KeyEvent/VK_F7
  :f8 java.awt.event.KeyEvent/VK_F8
  :f9 java.awt.event.KeyEvent/VK_F9
  :final java.awt.event.KeyEvent/VK_FINAL
  :find java.awt.event.KeyEvent/VK_FIND
  :full_width java.awt.event.KeyEvent/VK_FULL_WIDTH
  :g java.awt.event.KeyEvent/VK_G
  :greater java.awt.event.KeyEvent/VK_GREATER
  :h java.awt.event.KeyEvent/VK_H
  :half_width java.awt.event.KeyEvent/VK_HALF_WIDTH
  :help java.awt.event.KeyEvent/VK_HELP
  :hiragana java.awt.event.KeyEvent/VK_HIRAGANA
  :home java.awt.event.KeyEvent/VK_HOME
  :i java.awt.event.KeyEvent/VK_I
  :input_method_on_off java.awt.event.KeyEvent/VK_INPUT_METHOD_ON_OFF
  :insert java.awt.event.KeyEvent/VK_INSERT
  :inverted_exclamation_mark java.awt.event.KeyEvent/VK_INVERTED_EXCLAMATION_MARK
  :j java.awt.event.KeyEvent/VK_J
  :japanese_hiragana java.awt.event.KeyEvent/VK_JAPANESE_HIRAGANA
  :japanese_katakana java.awt.event.KeyEvent/VK_JAPANESE_KATAKANA
  :japanese_roman java.awt.event.KeyEvent/VK_JAPANESE_ROMAN
  :k java.awt.event.KeyEvent/VK_K
  :kana java.awt.event.KeyEvent/VK_KANA
  :kana_lock java.awt.event.KeyEvent/VK_KANA_LOCK
  :kanji java.awt.event.KeyEvent/VK_KANJI
  :katakana java.awt.event.KeyEvent/VK_KATAKANA
  :kp_down java.awt.event.KeyEvent/VK_KP_DOWN
  :kp_left java.awt.event.KeyEvent/VK_KP_LEFT
  :kp_right java.awt.event.KeyEvent/VK_KP_RIGHT
  :kp_up java.awt.event.KeyEvent/VK_KP_UP
  :l java.awt.event.KeyEvent/VK_L
  :left java.awt.event.KeyEvent/VK_LEFT
  :left_parenthesis java.awt.event.KeyEvent/VK_LEFT_PARENTHESIS
  :less java.awt.event.KeyEvent/VK_LESS
  :m java.awt.event.KeyEvent/VK_M
  :meta java.awt.event.KeyEvent/VK_META
  :minus java.awt.event.KeyEvent/VK_MINUS
  :modechange java.awt.event.KeyEvent/VK_MODECHANGE
  :multiply java.awt.event.KeyEvent/VK_MULTIPLY
  :n java.awt.event.KeyEvent/VK_N
  :nonconvert java.awt.event.KeyEvent/VK_NONCONVERT
  :number_sign java.awt.event.KeyEvent/VK_NUMBER_SIGN
  :numpad0 java.awt.event.KeyEvent/VK_NUMPAD0
  :numpad1 java.awt.event.KeyEvent/VK_NUMPAD1
  :numpad2 java.awt.event.KeyEvent/VK_NUMPAD2
  :numpad3 java.awt.event.KeyEvent/VK_NUMPAD3
  :numpad4 java.awt.event.KeyEvent/VK_NUMPAD4
  :numpad5 java.awt.event.KeyEvent/VK_NUMPAD5
  :numpad6 java.awt.event.KeyEvent/VK_NUMPAD6
  :numpad7 java.awt.event.KeyEvent/VK_NUMPAD7
  :numpad8 java.awt.event.KeyEvent/VK_NUMPAD8
  :numpad9 java.awt.event.KeyEvent/VK_NUMPAD9
  :num_lock java.awt.event.KeyEvent/VK_NUM_LOCK
  :o java.awt.event.KeyEvent/VK_O
  :open_bracket java.awt.event.KeyEvent/VK_OPEN_BRACKET
  :p java.awt.event.KeyEvent/VK_P
  :page_down java.awt.event.KeyEvent/VK_PAGE_DOWN
  :page_up java.awt.event.KeyEvent/VK_PAGE_UP
  :paste java.awt.event.KeyEvent/VK_PASTE
  :pause java.awt.event.KeyEvent/VK_PAUSE
  :period java.awt.event.KeyEvent/VK_PERIOD
  :plus java.awt.event.KeyEvent/VK_PLUS
  :previous_candidate java.awt.event.KeyEvent/VK_PREVIOUS_CANDIDATE
  :printscreen java.awt.event.KeyEvent/VK_PRINTSCREEN
  :props java.awt.event.KeyEvent/VK_PROPS
  :q java.awt.event.KeyEvent/VK_Q
  :quote java.awt.event.KeyEvent/VK_QUOTE
  :quotedbl java.awt.event.KeyEvent/VK_QUOTEDBL
  :r java.awt.event.KeyEvent/VK_R
  :right java.awt.event.KeyEvent/VK_RIGHT
  :right_parenthesis java.awt.event.KeyEvent/VK_RIGHT_PARENTHESIS
  :roman_characters java.awt.event.KeyEvent/VK_ROMAN_CHARACTERS
  :s java.awt.event.KeyEvent/VK_S
  :scroll_lock java.awt.event.KeyEvent/VK_SCROLL_LOCK
  :semicolon java.awt.event.KeyEvent/VK_SEMICOLON
  :separater java.awt.event.KeyEvent/VK_SEPARATER
  :separator java.awt.event.KeyEvent/VK_SEPARATOR
  :shift java.awt.event.KeyEvent/VK_SHIFT
  :slash java.awt.event.KeyEvent/VK_SLASH
  :space java.awt.event.KeyEvent/VK_SPACE
  :stop java.awt.event.KeyEvent/VK_STOP
  :subtract java.awt.event.KeyEvent/VK_SUBTRACT
  :t java.awt.event.KeyEvent/VK_T
  :tab java.awt.event.KeyEvent/VK_TAB
  :u java.awt.event.KeyEvent/VK_U
  :undefined java.awt.event.KeyEvent/VK_UNDEFINED
  :underscore java.awt.event.KeyEvent/VK_UNDERSCORE
  :undo java.awt.event.KeyEvent/VK_UNDO
  :up java.awt.event.KeyEvent/VK_UP
  :v java.awt.event.KeyEvent/VK_V
  :w java.awt.event.KeyEvent/VK_W
  :windows java.awt.event.KeyEvent/VK_WINDOWS
  :x java.awt.event.KeyEvent/VK_X
  :y java.awt.event.KeyEvent/VK_Y
  :z java.awt.event.KeyEvent/VK_Z})
